### ISSUE TITLE
Make rename highlighting less visible

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-hediet-power-tools#5]

**Comment by Gruntfuggly** [comment]
This would be great - I use a very small font and the highlight makes the text unreadable.

**Comment by hediet** [comment]
Do you use the latest version? I've already changed it to a black dashed border. Or is that still to much?
I played a little bit around with it, but it's very hard to find something suitable...

**Comment by hediet** [comment]
Do you use the latest version? I've already changed it to a black dashed border like this:
![image](https://user-images.githubusercontent.com/2931520/86264919-683bfc80-bbc3-11ea-918a-c074708f9678.png)

Or is that still to much?

Previously it was like this:
![image](https://user-images.githubusercontent.com/2931520/86264801-3fb40280-bbc3-11ea-9adc-df5a4aa3b08c.png)


I played a little bit around with it, but it's very hard to find something suitable...

Do you have ideas?

**Comment by Gruntfuggly** [comment]
I use a dark theme so it looks like this for me (the error lens isn't helping either, but that's not your fault!):

![image](https://user-images.githubusercontent.com/376658/86265247-75ed8400-bbbb-11ea-858d-2dda3c784ebe.png)

I understand the problem though - in my own extension I ended up adding lots of configuration options for highlights because everybody seems to want something different. 

If I'm honest, the background colour works well enough for me.

What is also annoying is that it's not simple to just pass straight CSS into vscode's highlights.

**Comment by hediet** [comment]
I see. I think I will add some options too.

Btw. nice extension you have there ;) It's sad that VS Code does not expose its bundled ripgrep, since it also searches in unsaved files...

**Comment by Gruntfuggly** [comment]
Hmm, I thought it should be working with unsaved files. I'll have to check that. Ah - it highlights in the unsaved files, but doesn't add them to the tree - not sure where it would put them? I could add an unsaved node...

**Comment by hediet** [comment]
There is now (0.2.2) this:
![image](https://user-images.githubusercontent.com/2931520/86508304-5f277700-bddf-11ea-8816-549d1fc9200c.png)

If you want other themes, please open a pull request!

Just add your theme [here](https://github.com/hediet/vscode-hediet-power-tools/blob/dfea7f48187f077d628b9c6909410e210d0f062c/src/features/ChangeTracker.ts#L33), add a new enum entry in package.json for the theme [here](https://github.com/hediet/vscode-hediet-power-tools/blob/dfea7f48187f077d628b9c6909410e210d0f062c/package.json#L71)
and add a screenshot to README.md.

**Comment by Gruntfuggly** [comment]
I've been using this for the past few days and the colored theme works really well for me. Thank you!

**Comment by hediet** [comment]
Thanks ;) I'm thinking of only renaming the identifiers that intersect any of the active selections - I accidentally renamed something I didn't want to rename. What do you think of that?

**Comment by Gruntfuggly** [comment]
Sounds like a useful option. I did the same thing at one point, but I put it down to vscode being over zealous with it's search.
Maybe a report on what was renamed would be useful in the output panel? I don't know if it is possible to get that information though?
